Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Metrics/LineLength:
  Max: 100
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Style/NumericLiterals:
  Enabled: false
