language: ruby
rvm:
- 2.4.1
cache: bundler
env:
  global:
  - RACK_ENV=test
  - SESSION_SECRET=hjasgdahjdgakjshdgaskdgaskjdgakg
services:
- postgresql
addons:
  postgresql: '9.4'
install:
- bundle install
- psql -c 'create database giftionary_test;' -U postgres
- rake db:migrate
script:
- rake
